[CmdletBinding()]
param([Parameter(ValueFromRemainingArguments=$true)][string[]]$ApplicationArgs)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Fail([string]$Code){throw "bootstrap_error:$Code"}
function Hash([string]$File){(Get-FileHash -LiteralPath $File -Algorithm SHA256).Hash.ToLowerInvariant()}
function LockValue([string]$Name){$p=$script:Lock.PSObject.Properties[$Name];if($null -eq $p -or $null -eq $p.Value -or [string]::IsNullOrEmpty([string]$p.Value)){Fail "lock_value_$Name"};[string]$p.Value}
function LockNumber([string]$Name){$text=LockValue $Name;$value=0L;if(-not [long]::TryParse($text,[ref]$value)-or$value-lt 0){Fail "lock_number_$Name"};$value}
function RequireSha([string]$Value){if($Value-notmatch'^[0-9a-f]{64}$'){Fail 'invalid_sha256'}}
function Relative([string]$Value){if([string]::IsNullOrEmpty($Value)-or[IO.Path]::IsPathRooted($Value)-or$Value.Contains('\')-or$Value.Contains(':')){Fail 'unsafe_relative_path'};foreach($part in $Value.Split('/')){if([string]::IsNullOrEmpty($part)-or$part-eq'.'-or$part-eq'..'-or$part.StartsWith('-')-or$part.EndsWith('.')-or$part.EndsWith(' ')){Fail 'unsafe_relative_path'}};$Value}
function InitialUri([string]$Value){$uri=[Uri]$Value;if($uri.Scheme-ne'https'-or-not[string]::IsNullOrEmpty($uri.UserInfo)-or-not[string]::IsNullOrEmpty($uri.Query)-or-not[string]::IsNullOrEmpty($uri.Fragment)){Fail 'unsafe_distribution_url'};$ok=($uri.Host-eq'github.com'-and$uri.AbsolutePath-match'^/[^/]+/[^/]+/releases/download/[^/]+/[^/]+$')-or($uri.Host-eq'nodejs.org'-and$uri.AbsolutePath-match'^/dist/v[0-9]+\.[0-9]+\.[0-9]+/[^/]+$')-or($uri.Host-eq'registry.npmjs.org'-and$uri.AbsolutePath-match'/-/[^/]+-[0-9]+\.[0-9]+\.[0-9]+\.tgz$');if(-not$ok){Fail 'unsafe_distribution_url'};$uri}
function RedirectUri([Uri]$Base,[string]$Location){$uri=[Uri]::new($Base,$Location);if($uri.Scheme-ne'https'-or$uri.Host-notin@('github.com','nodejs.org','registry.npmjs.org','release-assets.githubusercontent.com','objects.githubusercontent.com')){Fail 'unsafe_redirect'};$uri}
function Download([string]$Url,[string]$Target,[long]$Maximum){$uri=InitialUri $Url;$handler=[Net.Http.HttpClientHandler]::new();$handler.AllowAutoRedirect=$false;$client=[Net.Http.HttpClient]::new($handler);$client.Timeout=[TimeSpan]::FromMinutes(10);try{for($redirect=0;$redirect-le 5;$redirect++){ $response=$client.GetAsync($uri,[Net.Http.HttpCompletionOption]::ResponseHeadersRead).GetAwaiter().GetResult();try{$status=[int]$response.StatusCode;if($status-in@(301,302,303,307,308)){if($redirect-eq 5-or$null-eq$response.Headers.Location){Fail 'download_redirect'};$uri=RedirectUri $uri ([string]$response.Headers.Location);continue};if($status-ne 200){Fail 'download_http'};if($response.Content.Headers.ContentLength.HasValue-and$response.Content.Headers.ContentLength.Value-ne$Maximum){Fail 'download_size'};$input=$response.Content.ReadAsStreamAsync().GetAwaiter().GetResult();$output=[IO.File]::Open($Target,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$buffer=New-Object byte[] 81920;$total=0L;while(($read=$input.Read($buffer,0,$buffer.Length))-gt 0){$total+=$read;if($total-gt$Maximum){Fail 'download_size'};$output.Write($buffer,0,$read)};$output.Flush($true);if($total-ne$Maximum){Fail 'download_size'};return}finally{$output.Dispose();$input.Dispose()}}finally{$response.Dispose()}};Fail 'download_redirect'}finally{$client.Dispose();$handler.Dispose()}}
function VerifyFile([string]$File,[long]$Bytes,[string]$Sha){if(-not(Test-Path -LiteralPath $File -PathType Leaf)-or((Get-Item -LiteralPath $File).Attributes-band[IO.FileAttributes]::ReparsePoint)){Fail 'missing_regular_file'};if((Get-Item -LiteralPath $File).Length-ne$Bytes){Fail 'file_size_mismatch'};if((Hash $File)-ne$Sha){Fail 'file_sha256_mismatch'}}
function ReadExpected([string]$Integrity,[string]$IntegritySha,[int]$ExpectedCount){if(-not(Test-Path -LiteralPath $Integrity)){Fail 'missing_integrity_file'};if((Hash $Integrity)-ne$IntegritySha){Fail 'integrity_file_changed'};$lines=@(Get-Content -LiteralPath $Integrity);if($lines.Count-ne$ExpectedCount){Fail 'checksum_count_mismatch'};$expected=@{};foreach($line in$lines){if($line-notmatch'^([0-9a-f]{64})  (.+)$'){Fail 'malformed_checksum_line'};$relative=Relative $Matches[2];$expected[$relative]=$Matches[1]};$expected}
function VerifyRoot([string]$Root,[string]$IntegrityRelative,[string]$IntegritySha,[int]$ExpectedCount){$integrity=Join-Path $Root ($IntegrityRelative.Replace('/',[IO.Path]::DirectorySeparatorChar));$expected=ReadExpected $integrity $IntegritySha $ExpectedCount;$links=Get-ChildItem -LiteralPath $Root -Recurse -Force|Where-Object{($_.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne 0};if($links){Fail 'component_contains_link'};foreach($relative in$expected.Keys){$file=Join-Path $Root ($relative.Replace('/',[IO.Path]::DirectorySeparatorChar));if(-not(Test-Path -LiteralPath $file -PathType Leaf)-or(Hash $file)-ne$expected[$relative]){Fail 'component_file_changed'}};$files=@(Get-ChildItem -LiteralPath $Root -Recurse -Force -File);if($files.Count-ne($ExpectedCount+1)){Fail 'component_has_extra_file'};$expected}
function VerifyArchive([string]$Archive,[hashtable]$Expected,[string]$IntegrityRelative){$tar=Join-Path $env:SystemRoot 'System32\tar.exe';$names=@(&$tar -tzf $Archive);if($LASTEXITCODE-ne 0-or$names.Count-ne($Expected.Count+1)){Fail 'archive_inventory'};foreach($name in$names){$safe=Relative $name;if($safe-ne$IntegrityRelative-and-not$Expected.ContainsKey($safe)){Fail 'archive_inventory'}};$verbose=@(&$tar -tvzf $Archive);if($LASTEXITCODE-ne 0){Fail 'archive_list'};foreach($line in$verbose){if(-not$line.StartsWith('-')){Fail 'archive_non_regular'}}}
function Quote([string]$Value){if($Value.Length-eq 0){return'""'};if($Value-notmatch'[\s"]'){return$Value};$result='"';$slashes=0;foreach($c in$Value.ToCharArray()){if($c-eq'\'){$slashes++;continue};if($c-eq'"'){$result+=('\\'*(2*$slashes+1))+'"'}else{$result+=('\\'*$slashes)+$c};$slashes=0};$result+=('\\'*(2*$slashes))+'"';$result}
$LockPath=Join-Path $PSScriptRoot 'bootstrap-lock.json';if(-not(Test-Path -LiteralPath $LockPath -PathType Leaf)){Fail 'missing_adjacent_lock'};$script:Lock=Get-Content -LiteralPath $LockPath -Raw|ConvertFrom-Json;if((LockValue schema)-ne'tiangong-lca.runtime-bootstrap-lock.v1'-or(LockValue bootstrap_protocol)-ne'tiangong-lca.runtime-bootstrap.v1'){Fail 'lock_protocol'};$selfSha=LockValue powershell_script_sha256;RequireSha $selfSha;if((Hash $PSCommandPath)-ne$selfSha){Fail 'bootstrap_script_changed'}
if(-not[Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([Runtime.InteropServices.OSPlatform]::Windows)-or[Runtime.InteropServices.RuntimeInformation]::OSArchitecture-ne[Runtime.InteropServices.Architecture]::X64){Fail 'windows_x64_required'};$platform='win32_x64'
$manifestUrl=LockValue manifest_url;$manifestBytes=LockNumber manifest_bytes;$manifestSha=LockValue manifest_sha256;RequireSha $manifestSha;$componentKey=LockValue "${platform}_component_key";RequireSha $componentKey;$archiveUrl=LockValue "${platform}_archive_url";$archiveBytes=LockNumber "${platform}_archive_bytes";$archiveSha=LockValue "${platform}_archive_sha256";RequireSha $archiveSha;$integrityRelative=Relative (LockValue "${platform}_integrity_path");$integritySha=LockValue "${platform}_integrity_sha256";RequireSha $integritySha;$fileCount=[int](LockNumber "${platform}_file_count");$nodeRelative=Relative (LockValue "${platform}_node_path");$cliRelative=Relative (LockValue "${platform}_cli_path");$entry=LockValue app_entry
$base=if($env:LOCALAPPDATA){$env:LOCALAPPDATA}else{Join-Path $env:USERPROFILE 'AppData\Local'};$cache=Join-Path $base 'tiangong-lca\runtimes\v1';$marker=Join-Path $cache '.runtime-cache.json';[IO.Directory]::CreateDirectory($cache)|Out-Null;if(Test-Path -LiteralPath $marker){if((Get-Content -LiteralPath $marker -Raw).Trim()-ne'{"schema":"tiangong-lca.runtime-cache.v1"}'){Fail 'cache_marker_invalid'}}else{$entries=@(Get-ChildItem -LiteralPath $cache -Force);if($entries.Count-ne 0-and-not(Test-Path -LiteralPath $marker)-and@($entries|Where-Object{-not$_.Name.StartsWith('.runtime-cache.json.')-or-not$_.Name.EndsWith('.tmp')}).Count-ne 0){Fail 'cache_not_owned'};$markerTemp="$marker.$PID.tmp";[IO.File]::WriteAllText($markerTemp,"{`"schema`":`"tiangong-lca.runtime-cache.v1`"}`n",[Text.UTF8Encoding]::new($false));try{[IO.File]::Move($markerTemp,$marker)}catch{Remove-Item -LiteralPath $markerTemp -Force -ErrorAction SilentlyContinue;if(-not(Test-Path -LiteralPath $marker)-or(Get-Content -LiteralPath $marker -Raw).Trim()-ne'{"schema":"tiangong-lca.runtime-cache.v1"}'){Fail 'cache_marker_invalid'}}}
$lockFile=Join-Path $cache '.bootstrap.lock';$lockStream=$null;for($wait=0;$wait-le 120;$wait++){try{$lockStream=[IO.File]::Open($lockFile,[IO.FileMode]::CreateNew,[IO.FileAccess]::ReadWrite,[IO.FileShare]::Read);$owner=[Text.Encoding]::UTF8.GetBytes("$PID|$([Environment]::MachineName)");$lockStream.Write($owner,0,$owner.Length);$lockStream.Flush($true);break}catch[IO.IOException]{if($wait-eq 120){Fail 'bootstrap_lock_timeout'};try{$owner=[IO.File]::ReadAllText($lockFile).Split('|');if($owner.Count-eq 2-and$owner[1]-eq[Environment]::MachineName-and$null-eq(Get-Process -Id ([int]$owner[0]) -ErrorAction SilentlyContinue)){Remove-Item -LiteralPath $lockFile -Force;continue}}catch{};Start-Sleep -Milliseconds 250}};if($null-eq$lockStream){Fail 'bootstrap_lock'}
$temp=Join-Path $cache ('.bootstrap-stage.'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($temp)|Out-Null;try{$manifestDir=Join-Path $cache 'manifests';$components=Join-Path $cache 'components';[IO.Directory]::CreateDirectory($manifestDir)|Out-Null;[IO.Directory]::CreateDirectory($components)|Out-Null;$manifest=Join-Path $manifestDir "$manifestSha.json";if(Test-Path -LiteralPath $manifest){VerifyFile $manifest $manifestBytes $manifestSha}else{$downloaded=Join-Path $temp 'manifest';Download $manifestUrl $downloaded $manifestBytes;VerifyFile $downloaded $manifestBytes $manifestSha;[IO.File]::Move($downloaded,$manifest)};$target=Join-Path $components $componentKey;$root=Join-Path $target 'root';if(Test-Path -LiteralPath $root){VerifyRoot $root $integrityRelative $integritySha $fileCount|Out-Null}else{if(Test-Path -LiteralPath $target){Fail 'incomplete_component'};$archive=Join-Path $temp 'component.tar.gz';Download $archiveUrl $archive $archiveBytes;VerifyFile $archive $archiveBytes $archiveSha;$checks=Join-Path $temp 'checks';$checkFile=Join-Path $checks ($integrityRelative.Replace('/',[IO.Path]::DirectorySeparatorChar));[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($checkFile))|Out-Null;$tar=Join-Path $env:SystemRoot 'System32\tar.exe';&$tar -xzf $archive -C $checks $integrityRelative;if($LASTEXITCODE-ne 0){Fail 'integrity_extract'};$expected=ReadExpected $checkFile $integritySha $fileCount;VerifyArchive $archive $expected $integrityRelative;$extract=Join-Path $temp 'root';[IO.Directory]::CreateDirectory($extract)|Out-Null;&$tar -xzf $archive -C $extract;if($LASTEXITCODE-ne 0){Fail 'archive_extract'};VerifyRoot $extract $integrityRelative $integritySha $fileCount|Out-Null;$publish=Join-Path $temp 'component';[IO.Directory]::CreateDirectory($publish)|Out-Null;[IO.Directory]::Move($extract,(Join-Path $publish 'root'));[IO.Directory]::Move($publish,$target)};$node=Join-Path $root ($nodeRelative.Replace('/',[IO.Path]::DirectorySeparatorChar));$cli=Join-Path $root ($cliRelative.Replace('/',[IO.Path]::DirectorySeparatorChar));VerifyFile $node (Get-Item $node).Length (Hash $node);VerifyFile $cli (Get-Item $cli).Length (Hash $cli)
$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName=$node;$arguments=@($cli,'runtime','exec','--manifest',$manifest,'--manifest-sha256',$manifestSha,'--cache-dir',$cache,'--entry',$entry,'--cwd',(Get-Location).Path,'--')+$ApplicationArgs;$psi.Arguments=($arguments|ForEach-Object{Quote $_})-join' ';$psi.UseShellExecute=$false;$psi.EnvironmentVariables.Clear();foreach($name in@('HOME','USERPROFILE','PATH','PATHEXT','SystemRoot','SYSTEMROOT','WINDIR','ComSpec','COMSPEC','APPDATA','LOCALAPPDATA','XDG_CONFIG_HOME','XDG_CACHE_HOME','TEMP','TMP','LANG','LC_ALL','TZ','TIANGONG_LCA_API_BASE_URL','TIANGONG_LCA_SUPABASE_PUBLISHABLE_KEY','TIANGONG_LCA_OAUTH_CLIENT_ID','TIANGONG_LCA_OAUTH_REDIRECT_URI','TIANGONG_LCA_REGION','TIANGONG_LCA_AUTH_MODE','TIANGONG_LCA_SESSION_FILE','TIANGONG_LCA_DISABLE_SESSION_CACHE','TIANGONG_LCA_FORCE_REAUTH','TIANGONG_LCA_ACCESS_TOKEN')){if(Test-Path "Env:$name"){$psi.EnvironmentVariables[$name]=(Get-Item "Env:$name").Value}};$process=[Diagnostics.Process]::Start($psi);$process.WaitForExit();exit $process.ExitCode}finally{if(Test-Path -LiteralPath $temp){Remove-Item -LiteralPath $temp -Recurse -Force};if($null-ne$lockStream){$lockStream.Dispose();Remove-Item -LiteralPath $lockFile -Force -ErrorAction SilentlyContinue}}
